default_roles:
  - bash
  - c
  - git
  - nix
  - nvim
  - opencode
  - openssh
  - ssh
  - tailscale
  # - test
  - ufw
  - users
  - zellij
  - zsh

exclude_roles:
  - bootstrap

# Default values for system facts
facts_op_installed: false
facts_nix_installed: false
facts_home_manager_installed: false
facts_zsh_installed: false
facts_tailscale_installed: false
facts_tailscale_authed: false

# Users facts
facts_sillypoise_exists: false
facts_flubber_exists: false
facts_password_setup_complete: false

# Define usernames
host_user: "sillypoise"
automated_user: "flubber"
gh_user: "sillypoise"

# Define home directories based on usernames, with fallback for host_user
host_user_home: "/home/{{ host_user  }}"
automated_user_home: "/home/{{ automated_user }}"

# Define configs

facts_bash_config_installed: false
facts_zsh_config_installed: false
