---
# roles/zellij/tasks/main.yml
- name: Ensure zellij config directory exists
  ansible.builtin.file:
    path: "{{ host_user_home }}/.config/zellij"
    state: directory
    mode: '0755'
    owner: "{{ host_user }}"
    group: "{{ host_user }}"
  tags:
    - zellij
    - config

- name: Copy zellij config file
  ansible.builtin.copy:
    src: config.kdl
    dest: "{{ host_user_home }}/.config/zellij/config.kdl"
    mode: '0644'
    owner: "{{ host_user }}"
    group: "{{ host_user }}"
  tags:
    - zellij
    - config
